-- DAY 5 SQL BUSINESS QUERIES

-- CREATE REVENUE COLUMN
-- Revenue is calculated as Quantity × UnitPrice


ALTER TABLE orders
ADD COLUMN Revenue DECIMAL(12,2);

UPDATE orders
SET Revenue = Quantity * UnitPrice;


-- BUSINESS QUESTIONS


-- 1. How many transactions are recorded in the dataset?This counts the total number of transactions

SELECT COUNT(*) AS transaction_count
FROM orders;


-- 2. What is the total revenue generated from all transactions?This adds all the revenue generated to gain the total revenue

SELECT SUM(Revenue) AS total_revenue
FROM orders;


-- 3. What is the average value of a transaction? This shows the average revenue per transaction

SELECT AVG(Revenue) AS average_order_value
FROM orders;


-- 4. What is the total revenue generated in each month?This shows the revenue generated by each month and is arranged from the largest to the lowest but the format of the date needs to be changed to DATE

SELECT
    DATE_FORMAT(STR_TO_DATE(OrderDate, '%d/%m/%Y'), '%Y-%m') AS month,
    SUM(Revenue) AS monthly_revenue
FROM orders
GROUP BY month
ORDER BY month;


-- 5. Which 5 Product IDs generated the most revenue? This displays the first 5 productIDs with the largest revenue and is grouped in descending order

SELECT
    ProductID,
    SUM(Revenue) AS total_revenue
FROM orders
GROUP BY ProductID
ORDER BY total_revenue DESC
LIMIT 5;


-- 6. Which month had the most transactions?This shows the months with the highest number of transactions and the results are arranged in descending order 

SELECT
    DATE_FORMAT(STR_TO_DATE(OrderDate, '%d/%m/%Y'), '%Y-%m') AS month,
    COUNT(*) AS transaction_count
FROM orders
GROUP BY month
ORDER BY transaction_count DESC
LIMIT 1;


-- 7. What are the minimum and maximum unit prices?This shows the both highest and the lowest unitprices of the products 

SELECT
    MIN(UnitPrice) AS minimum_unit_price,
    MAX(UnitPrice) AS maximum_unit_price
FROM orders;


-- 8. How many transactions did each salesperson handle? This shows the the number of transactions handled by each salesperson and the results are grouped from the highest to the lowest 

SELECT
    Salesperson,
    COUNT(*) AS transaction_count
FROM orders
GROUP BY Salesperson
ORDER BY transaction_count DESC;


-- 9. How much revenue did each salesperson generate? This shows the revenue each salesperson generated and is arranged in descending order

SELECT
    Salesperson,
    SUM(Revenue) AS total_revenue
FROM orders
GROUP BY Salesperson
ORDER BY total_revenue DESC;


-- 10. Which payment methods are used most frequently? This counts how frequently the payment methods are used in each transaction and is sorted in descending order

SELECT
    PaymentMethod,
    COUNT(*) AS transaction_count
FROM orders
GROUP BY PaymentMethod
ORDER BY transaction_count DESC;