-- DAY 6: ADVANCED SQL ANALYSIS
-- Database: data_analytics


-- QUERY 1: TOP CUSTOMERS BY REVENUE
-- Finds the 10 customers who generated the highest revenue.
-- Revenue = Quantity × UnitPrice
SELECT
    c.CustomerID,
    c.CustomerName,
    SUM(o.Quantity * o.UnitPrice) AS TotalRevenue
FROM orders AS o
JOIN customers AS c
    ON o.CustomerID = c.CustomerID
GROUP BY
    c.CustomerID,
    c.CustomerName
ORDER BY TotalRevenue DESC
LIMIT 10;


-- QUERY 2: REVENUE BY REGION
-- Connects orders to customers so we can calculate
-- the total revenue generated in each region.
SELECT
    c.Region,
    SUM(o.Quantity * o.UnitPrice) AS TotalRevenue
FROM orders AS o
JOIN customers AS c
    ON o.CustomerID = c.CustomerID
GROUP BY c.Region
ORDER BY TotalRevenue DESC;


-- QUERY 3: REVENUE BY PRODUCT CATEGORY
-- Connects orders to products to find the total
-- revenue generated by each product category.
SELECT
    p.Category,
    SUM(o.Quantity * o.UnitPrice) AS TotalRevenue
FROM orders AS o
JOIN products AS p
    ON o.ProductID = p.ProductID
GROUP BY p.Category
ORDER BY TotalRevenue DESC;


-- QUERY 4: PRODUCT PERFORMANCE BY REGION
-- Shows the revenue generated by each product
-- within each region.
SELECT
    c.Region,
    p.ProductName,
    SUM(o.Quantity * o.UnitPrice) AS TotalRevenue
FROM orders AS o
JOIN customers AS c
    ON o.CustomerID = c.CustomerID
JOIN products AS p
    ON o.ProductID = p.ProductID
GROUP BY
    c.Region,
    p.ProductName
ORDER BY
    c.Region,
    TotalRevenue DESC;


-- QUERY 5: CUSTOMERS WITH NO MATCHING ORDERS
-- LEFT JOIN keeps every customer.
-- Customers whose order ID is NULL have no matching order.
SELECT
    c.CustomerID,
    c.CustomerName
FROM customers AS c
LEFT JOIN orders AS o
    ON c.CustomerID = o.CustomerID
WHERE o.CustomerID IS NULL;


-- QUERY 6: NUMBER OF ORDERS PER CUSTOMER
-- Counts how many orders are associated with each customer.
-- LEFT JOIN also allows customers with zero orders to appear.
SELECT
    c.CustomerID,
    c.CustomerName,
    COUNT(o.OrderID) AS NumberOfOrders
FROM customers AS c
LEFT JOIN orders AS o
    ON c.CustomerID = o.CustomerID
GROUP BY
    c.CustomerID,
    c.CustomerName
ORDER BY NumberOfOrders DESC;


-- QUERY 7: PRODUCT PERFORMANCE
-- Calculates the total revenue generated by each product.
SELECT
    p.ProductID,
    p.ProductName,
    p.Category,
    SUM(o.Quantity * o.UnitPrice) AS TotalRevenue
FROM products AS p
JOIN orders AS o
    ON p.ProductID = o.ProductID
GROUP BY
    p.ProductID,
    p.ProductName,
    p.Category
ORDER BY TotalRevenue DESC;


-- QUERY 8: CUSTOMER REVENUE USING A CTE
-- The CTE creates a temporary result called CustomerRevenue.
-- We then use that result to display customers from
-- highest to lowest total revenue.
WITH CustomerRevenue AS (
    SELECT
        c.CustomerID,
        c.CustomerName,
        SUM(o.Quantity * o.UnitPrice) AS TotalRevenue
    FROM customers AS c
    JOIN orders AS o
        ON c.CustomerID = o.CustomerID
    GROUP BY
        c.CustomerID,
        c.CustomerName
)
SELECT *
FROM CustomerRevenue
ORDER BY TotalRevenue DESC;


-- QUERY 9: BEST PRODUCT BY REGION
-- First calculates revenue for every product in every region.
-- ROW_NUMBER() ranks products within each region.
-- We then keep only rank 1, giving the highest-revenue
-- product in each region.
WITH RegionProductRevenue AS (
    SELECT
        c.Region,
        p.ProductName,
        SUM(o.Quantity * o.UnitPrice) AS TotalRevenue
    FROM orders AS o
    JOIN customers AS c
        ON o.CustomerID = c.CustomerID
    JOIN products AS p
        ON o.ProductID = p.ProductID
    GROUP BY
        c.Region,
        p.ProductName
),
RankedProducts AS (
    SELECT
        Region,
        ProductName,
        TotalRevenue,
        ROW_NUMBER() OVER (
            PARTITION BY Region
            ORDER BY TotalRevenue DESC
        ) AS rn
    FROM RegionProductRevenue
)
SELECT
    Region,
    ProductName,
    TotalRevenue
FROM RankedProducts
WHERE rn = 1
ORDER BY Region;

